### ISSUE TITLE
error when running "python manage.py migrate"

### ISSUE THREAD

**Issue by xuebashuoge** [Pi-SK/Dividend_Spider#1]
**Environment:** 
- ubuntu 20.04
- SQL Server 2022
- ODBC driver 17
- python 3.10
-     pip package: 
-     Django               5.0.9
-     django-appconf       1.0.6
-     django-crispy-forms  2.3
-     django-import-export 4.3.3
-     django-select2       8.2.1
-     mssql                1.0.1
-     mssql-django         1.5
-     pandas               2.2.3

**Database setting:**
In the sqlcmd, I created a database named 'stock‘. 
```
1> select name
2> from sys.databases;
3> go
name                                                                                                                            
--------------------------------------------------------------------------------------------------------------------------------
master                                                                                                                          
tempdb                                                                                                                          
model                                                                                                                           
msdb                                                                                                                            
stock                                                                                                                           

(5 rows affected)
```

In settings.py, I set the databases as follows.
```
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'stock',
        'HOST': '127.0.0.1',  
        'USER': 'sa', 
        'PASSWORD': '******', 
        'OPTIONS': {
        },
    }
}
```

**Running results:**
When I executed the script `python manage.py migrate`, I got the following errors.
`pyodbc.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'dividend_data_dividend'. (208) (SQLExecDirectW)")`
`django.db.utils.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'dividend_data_dividend'. (208) (SQLExecDirectW)")`

Is there anything wrong in my configuration? The complete output is attached in the following.
```
python manage.py migrate
Traceback (most recent call last):
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/mssql/base.py", line 677, in execute
    return self.cursor.execute(sql, params)
pyodbc.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'dividend_data_dividend'. (208) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Data/Git/Dividend_Spider/manage.py", line 22, in <module>
    main()
  File "/Data/Git/Dividend_Spider/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Data/Git/Dividend_Spider/dividend_spider/urls.py", line 22, in <module>
    path('dividends/', include('dividend_data.urls'))
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Data/Git/Dividend_Spider/dividend_data/urls.py", line 2, in <module>
    from . import views
  File "/Data/Git/Dividend_Spider/dividend_data/views.py", line 7, in <module>
    from .forms import QueryForm_Dividend
  File "/Data/Git/Dividend_Spider/dividend_data/forms.py", line 9, in <module>
    class QueryForm_Dividend(forms.Form):
  File "/Data/Git/Dividend_Spider/dividend_data/forms.py", line 10, in QueryForm_Dividend
    stock_code_choices = [('', '---------')] + list(Dividend.objects.order_by('stock_code').values_list('stock_code','stock_code').distinct())
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/db/models/query.py", line 248, in __iter__
    return compiler.results_iter(
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1513, in results_iter
    results = self.execute_sql(
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sugar/App/anaconda3/envs/stock/lib/python3.10/site-packages/mssql/base.py", line 677, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'dividend_data_dividend'. (208) (SQLExecDirectW)")
```

**Comment by Pi-SK** [comment]
我刚刚进行了测试，当我尝试重新配置一个新的数据库后，这个问题也在我的电脑上复现了。

在经过初步问题排查以及查询相关资料后，目前我也没有弄清导致这个问题出现的根本原因，不过，倒是发现了一个可以解决这个问题的直接方法：

进入./dividend_spider/urls.py，将

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dividends/', include('dividend_data.urls'))
]

中的path('dividends/', include('dividend_data.urls'))暂时注释掉，之后运行python manage.py makemigrations以及python manage.py migrate，这时发现错误不再出现。数据库迁移成功之后将之前的代码取消注释，接着运行python manage.py runserver，访问.../dividend_data/eastmoney/即可进入网页（这时候会显示数据为空，因为还需要先手动运行爬取程序）

希望这个回复能给你带来帮助




-------------------------------------

I just ran some tests, and the issue also occurred on my computer when I tried to reconfigure a new database.
After conducting initial problem-solving and researching relevant materials, I have not yet identified the underlying cause of the issue, but I have discovered a direct method to resolve the problem:

Go to the file "/dividend_spider/urls.py" and find the following line:
urlpatterns = [
path('admin/', admin.site.urls),
path('dividends/', include('dividend_data.urls'))
]
In the code, comment out the line `path('dividends/', include('dividend_data.urls'))` temporarily, then run `python manage.py makemigrations` and `python manage.py migrate`. At this point, you will find that the error no longer appears. Once the database migration is successful, uncomment the previous code, and then run `python manage.py runserver`. Access .../dividend_data/eastmoney/to enter the webpage (at this point, the data will be empty because manual crawling needs to be run first).

I hope this response will be helpful to you.

(translated by LLM)

-------------------------------------



At 2024-12-17 12:58:12, "xuebashuoge" ***@***.***> wrote:

Environment:

ubuntu 20.04
SQL Server 2022
ODBC driver 17
python 3.10
pip package: 

Django               5.0.9

django-appconf       1.0.6

django-crispy-forms  2.3

django-import-export 4.3.3

django-select2       8.2.1

mssql                1.0.1

mssql-django         1.5

pandas               2.2.3


Database setting:
In the sqlcmd, I created a database named 'stock‘.

1> select name
2> from sys.databases;
3> go
name                                                                                                                            
--------------------------------------------------------------------------------------------------------------------------------
master                                                                                                                          
tempdb                                                                                                                          
model                                                                                                                           
msdb                                                                                                                            
stock                                                                                                                           

(5 rows affected)


In settings.py, I set the databases as follows.

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'stock',
        'HOST': '127.0.0.1',  
        'USER': 'sa', 
        'PASSWORD': '******', 
        'OPTIONS': {
        },
    }
}


Running results:
When I executed the script python manage.py migrate, I got the following errors.
pyodbc.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'dividend_data_dividend'. (208) (SQLExecDirectW)")
django.db.utils.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'dividend_data_dividend'. (208) (SQLExecDirectW)")

Is there anything wrong in my configuration?

**Comment by xuebashuoge** [comment]
谢谢
